site_name: TMU AI Voice Agent Docs
site_description: Documentation for TMU AI Voice Agent
site_author: Cogent Infotech Interns
repo_url: https://github.com/Rhytham16/TMU-interns-ai-voice-agent

theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - toc.integrate

nav:
  - Home: index.md
  - Overview: overview.md
  - App: app.md
  - Load Documents: load_documents.md
  - Setup: setup.md
  - Structure: structure.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            heading_level: 2

markdown_extensions:
  - admonition
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.magiclink

dev_addr: 127.0.0.1:9000
